/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package itsxav.kotlin.com.cp1

fun Primatest(
    x: Int, divisor: Int = 2
)   :
        Boolean {
    if (x < 2)
        return false
    if (x == 2 || x == 3)
        return true
    if (x % divisor == 0)
        return false
    if (divisor + divisor > x)
        return true
    return Primatest(x, divisor + 1)
}

fun main() {
    val prime = readLine()!!.toInt()
    repeat(prime) {
        val x = readLine()!!.toInt()
        val result = if (Primatest(x)) "Prime Number"
        else "not Prime Number"
        println("Case #${it+1}: $result")
    }
}
